//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public int User { get; set; }
        public int State { get; set; }
        public string Address { get; set; }
        public int Pizza { get; set; }
        public decimal Cost { get; set; }
        public int TypeDelivery { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual OrdersStatu OrdersStatu { get; set; }
        public virtual Pizza Pizzas { get; set; }
        public virtual User Users { get; set; }
    }
}
