//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        public Pizza()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Size { get; set; }
        public int Count { get; set; }
        public decimal Price { get; set; }
        public string Describe { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Size Sizes { get; set; }
    }
}
